#!/bin/bash
# Simple, self-contained take on 'sub'
# Version 1

set -euo pipefail

main () {
    script="$(resolved_script_path "$0")"
    scriptname="${0##*/}"
    scriptdir="$(cd "$(dirname "$script")" && pwd -P)"
    PATH="$PATH:$scriptdir/libexec:$scriptdir/../libexec"

    command=
    if [ $# -gt 0 ]; then
        command="$1"
        shift
    fi

    evalf 'export _%s_ROOT="%s"' "$(echo "$scriptname" | tr '[:lower:]' '[:upper:]')" "$scriptdir"

    case "$command" in
        "" | "help" | "-h" | "--help")
            run_help "$@"
            ;;
        commands)
            run_commands "$@"
            ;;
        completions | "--complete")
            run_completions "$@"
            ;;
        init)
            run_init "$@"
            ;;
        *)
            # The -setup script is run to bootstrap before any other commands
            setup_path="$(command -v "$scriptname-sh--setup" 2>/dev/null)" || :
            if [ -n "$setup_path" ]; then
                eval "$(exec "$scriptname-sh--setup" "$@")"
            else
                setup_path="$(command -v "$scriptname--setup" 2>/dev/null)" || :
                if [ -n "$setup_path" ]; then
                    eval "\"$setup_path\""
                fi
            fi

            command_path="$(command -v "$scriptname-$command")" || die "command not found: $scriptname-$command"
            exec "$command_path" "$@"
            ;;
    esac
}

run_help () {
    command_path="$(command -v "$scriptname-help")" || :
    if [ -n "$command_path" ]; then
        exec "$command_path" "$@"
    else
        if [ $# -ne 0 ]; then
            if has_feature "$1" short_help; then
                exec "$script" "$1" "-h"
            elif has_feature "$1" help; then
                exec "$script" "$1" "--help"
            else
                echo >&2 "No help available for $1"
                return 1
            fi
        else
            echo >&2 "Usage: $scriptname COMMAND [ARGS..]"
            echo >&2
            echo >&2 "Available commands:"
            run_commands | sed 's,^,  ,' >&2
        fi
    fi
}

run_completions () {
    command_path="$(command -v "$scriptname-completions")" || :
    if [ -n "$command_path" ]; then
        exec "$command_path" "$@"
    else
        if [ $# -eq 0 ]; then
            echo commands
            echo completions
            printf '%s\n' '--complete'
            printf '%s\n' '-h'
            printf '%s\n' '--help'
            run_commands
        else
            subcommand="$1"
            shift
            if has_feature "$subcommand" completions; then
                exec "$script" "$subcommand" --complete "$@"
            else
                return 1
            fi

        fi
    fi
}

run_commands () {
    command_path="$(command -v "$scriptname-commands")" || :
    if [ -n "$command_path" ]; then
        exec "$command_path"
    else
        {
            echo help
            echo "$PATH" | tr ":" "\n" | while read -r path; do
                if [ -n "$path" ] && [ -z "${path##/*}" ]; then
                    for i in "$path/$scriptname-"*; do
                        if [ -x "$i" ]; then
                            basename -- "${i#$path/$scriptname-}"
                        fi
                    done
                fi
            done | grep -vx '\-setup' | grep -vx 'sh--setup'
        } | sort -u
    fi
}

run_init () {
    cat <<END
_${scriptname} () {
    if [ \$# -gt 0 ]; then
        ${scriptname}_command="\$1"
        shift
        command_path="\$(command -v ${scriptname}-sh-\$${scriptname}_command 2>/dev/null)" || :
        if [ -n "\$command_path" ]; then
            . "\$command_path" "\$@"
        else
            command ${scriptname} "\$${scriptname}_command" "\$@"
        fi
    else
        command ${scriptname}
    fi
}
alias ${scriptname}=_${scriptname}
END
}

has_feature () {
    command_path="$(command -v "$scriptname-sh-$1" 2>/dev/null)" || :
    if [ -z "$command_path" ]; then
        command_path="$(command -v "$scriptname-$1" 2>/dev/null)" || return 1
    fi
    sed -n -e "s/^# $scriptname: //p" "$command_path" | grep -Fwq "$2"
}

die () {
    echo >&2 "$@"
    exit 1
}

evalf () {
    fmt="$1"
    shift
    # printf >&2 "evalf: $fmt\n" "$@"
    # eval echo >&2 "evalf: $(printf "$fmt" "$@")"
    # shellcheck disable=SC2059
    eval "$(printf "$fmt" "$@")"
}

resolved_script_path () {
    script="$1"
    if [ ! -e "$script" ]; then
        if [ -n "${script##*/}" ]; then
            script="$(command -v "$script")"
        fi
        if [ ! -e "$script" ]; then
            echo >&2 "Error: unable to determine script location"
            exit 1
        fi
    fi

    while [ -L "$script" ]; do
        script="$(abs_readlink "$script")"
    done
    echo "$script"
}

abs_readlink () {
    for arg; do
        abspath "$(readlink "$arg")" "$(dirname "$arg")"
    done
}

abspath () {
    _path="$1"
    if [ -n "${_path##/*}" ]; then
        _path="${2:-$PWD}/$1"
    fi
    echo "$_path"
}

main "$@"
